---

- name: Setup Amazon linux
  include: Amazon.yml
  when: ansible_distribution == 'Amazon'
  tags:
  - system
  - nginx
  - build

- name: Setup Ubuntu
  include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
  - system
  - nginx
  - build

- name: Install packages
  package: name={{ item }} state=latest
  with_items: packages
  tags:
  - system
  - nginx
  - build

- name: Create instance_conf
  copy: src={{ instance_conf_bin }} dest=/{{ instance_conf_bin }} mode=0755 owner=root group=root
  tags:
  - config
  - nginx-config
  - build

- name: enable nginx
  service: name=nginx enabled=yes
  tags:
  - system
  - nginx
  - build
