---

- name: Set distro-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    -  default.yml 

- name: Install Development Tools
  package: name={{dev_tools}} state=latest
  tags:
    - system
    - build
    - packages
