---

- name: Setup Amazon linux
  include: Amazon.yml
  when: ansible_distribution == 'Amazon'
    - system
    - build
    - packages

- name: Setup Ubuntu
  include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
    - system
    - build
    - packages

- name: Install Development Tools
  package: name={{dev_tools}} state=latest
  tags:
    - system
    - build
    - packages
