---

- name: Setup Amazon linux
  include: Amazon.yml
  when: ansible_distribution == 'Amazon'
  tags:
    - system
    - build
    - rpmdevel

- name: Setup Ubuntu
  include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - system
    - build
    - rpmdevel

- name: Install RPM Dev Tools
  package: name={{ item }} state=latest
  with_items: packages
  tags:
    - system
    - build
    - rpmdevel

